/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoso2;

/**
 *
 * @author mkferrerteran
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PuntajeL = new javax.swing.JTextField();
        PuntajeB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        P2B = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        P1B = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        P3B = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        RefuerzoB = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        RefuerzoL = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        P3L = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        P2L = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        P1L = new javax.swing.JTextArea();
        circuitB = new javax.swing.JTextField();
        circuitL = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        winners = new javax.swing.JTextArea();
        timeB = new javax.swing.JTextField();
        time = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        timeL = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        contCarreras = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bugatti VS Lamborghini");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puntaje");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, 50));

        PuntajeL.setEditable(false);
        PuntajeL.setForeground(new java.awt.Color(0, 51, 51));
        PuntajeL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(PuntajeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 70, 30));

        PuntajeB.setEditable(false);
        PuntajeB.setForeground(new java.awt.Color(0, 51, 51));
        PuntajeB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(PuntajeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 70, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prioridad 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prioridad 3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prioridad 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Prioridad 2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 80, -1));

        jLabel8.setBackground(new java.awt.Color(0, 51, 51));
        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prioridad 2");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Reparando");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Prioridad 3");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Reparando");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        P2B.setEditable(false);
        P2B.setColumns(20);
        P2B.setForeground(new java.awt.Color(0, 51, 51));
        P2B.setRows(4);
        jScrollPane3.setViewportView(P2B);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 280, -1));

        P1B.setEditable(false);
        P1B.setColumns(20);
        P1B.setForeground(new java.awt.Color(0, 51, 51));
        P1B.setRows(4);
        jScrollPane2.setViewportView(P1B);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 280, -1));

        P3B.setEditable(false);
        P3B.setColumns(20);
        P3B.setForeground(new java.awt.Color(0, 51, 51));
        P3B.setRows(4);
        jScrollPane4.setViewportView(P3B);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 280, -1));

        jTextField2.setBackground(new java.awt.Color(0, 51, 51));
        jTextField2.setForeground(new java.awt.Color(0, 51, 51));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 90, 30));

        RefuerzoB.setEditable(false);
        RefuerzoB.setColumns(20);
        RefuerzoB.setForeground(new java.awt.Color(0, 51, 51));
        RefuerzoB.setRows(4);
        jScrollPane5.setViewportView(RefuerzoB);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 280, -1));

        RefuerzoL.setEditable(false);
        RefuerzoL.setColumns(20);
        RefuerzoL.setForeground(new java.awt.Color(0, 51, 51));
        RefuerzoL.setRows(4);
        RefuerzoL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane6.setViewportView(RefuerzoL);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 280, -1));

        P3L.setEditable(false);
        P3L.setColumns(20);
        P3L.setForeground(new java.awt.Color(0, 51, 51));
        P3L.setRows(4);
        jScrollPane7.setViewportView(P3L);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 280, -1));

        P2L.setEditable(false);
        P2L.setColumns(20);
        P2L.setForeground(new java.awt.Color(0, 51, 51));
        P2L.setRows(4);
        jScrollPane8.setViewportView(P2L);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 280, -1));

        P1L.setEditable(false);
        P1L.setColumns(20);
        P1L.setForeground(new java.awt.Color(0, 51, 51));
        P1L.setRows(4);
        jScrollPane9.setViewportView(P1L);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 280, -1));

        circuitB.setEditable(false);
        circuitB.setForeground(new java.awt.Color(0, 51, 51));
        circuitB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(circuitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 370, 80));

        circuitL.setEditable(false);
        circuitL.setForeground(new java.awt.Color(0, 51, 51));
        circuitL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(circuitL, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 370, 80));

        state.setEditable(false);
        state.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 160, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ganadores");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Estado");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 50, 20));

        winners.setEditable(false);
        winners.setColumns(20);
        winners.setForeground(new java.awt.Color(0, 51, 51));
        winners.setRows(5);
        jScrollPane1.setViewportView(winners);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 544, 370, 90));

        timeB.setEditable(false);
        timeB.setForeground(new java.awt.Color(0, 51, 51));
        timeB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        timeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBActionPerformed(evt);
            }
        });
        getContentPane().add(timeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 80, 30));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 50, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tiempo de recorrido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, 30));

        jTextField10.setBackground(new java.awt.Color(0, 51, 51));
        jTextField10.setForeground(new java.awt.Color(0, 51, 51));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 160, 30));

        timeL.setForeground(new java.awt.Color(0, 51, 51));
        timeL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        timeL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeLActionPerformed(evt);
            }
        });
        getContentPane().add(timeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 80, 30));

        jTextField11.setBackground(new java.awt.Color(0, 51, 51));
        jTextField11.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 90, 30));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cantidad de carreras");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, -1, -1));

        jTextField12.setBackground(new java.awt.Color(0, 51, 51));
        jTextField12.setForeground(new java.awt.Color(0, 51, 51));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 90, 30));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cambiar velociadad");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        contCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contCarrerasActionPerformed(evt);
            }
        });
        getContentPane().add(contCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, 80, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Captura de pantalla 2023-06-18 a la(s) 7.28.10 p. m..png"))); // NOI18N
        jLabel12.setMaximumSize(new java.awt.Dimension(1132, 659));
        jLabel12.setMinimumSize(new java.awt.Dimension(1132, 659));
        jLabel12.setPreferredSize(new java.awt.Dimension(1132, 659));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void timeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeBActionPerformed

    private void timeLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeLActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void contCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contCarrerasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea P1B;
    public javax.swing.JTextArea P1L;
    public javax.swing.JTextArea P2B;
    public javax.swing.JTextArea P2L;
    public javax.swing.JTextArea P3B;
    public javax.swing.JTextArea P3L;
    public javax.swing.JTextField PuntajeB;
    public javax.swing.JTextField PuntajeL;
    public javax.swing.JTextArea RefuerzoB;
    public javax.swing.JTextArea RefuerzoL;
    public javax.swing.JTextField circuitB;
    public javax.swing.JTextField circuitL;
    public static javax.swing.JTextField contCarreras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTextField state;
    public javax.swing.JSpinner time;
    public static javax.swing.JTextField timeB;
    public static javax.swing.JTextField timeL;
    public javax.swing.JTextArea winners;
    // End of variables declaration//GEN-END:variables
}
